FROM node:lts as build

ARG API_BASE_URL=http://localhost:8000

ENV VITE_API_BASE_URL=${API_BASE_URL}

WORKDIR /app
COPY ./ .
RUN npm install
RUN npm run build


FROM nginx:stable as runtime

RUN rm /etc/nginx/conf.d/default.conf
COPY env_conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]