FROM mambaorg/micromamba:latest as conda

RUN micromamba install --prefix /opt/conda blast -c bioconda -c conda-forge && \
	micromamba clean -aqy


FROM python:3.11-slim as runtime

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHOHUNBUFFERED=1

RUN apt-get update && \
	apt-get upgrade -y && \
	rm -rf /var/lib/apt/lists/*

# copy conda deps
COPY --from=conda /opt/conda /opt/conda
ENV PATH="/opt/conda/bin:$PATH"

COPY . /app/
WORKDIR /app

RUN --mount=from=ghcr.io/astral-sh/uv:0.5,source=/uv,target=/bin/uv \
    uv sync -nq --no-dev

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

RUN adduser --uid 1001 --system --no-create-home app
USER app

EXPOSE 8000
CMD ["sh", "/app/entrypoint.sh"]
