apiVersion: v1
kind: ConfigMap
metadata:
  name: peptipedia
data:
  TZ: "America/Santiago"
  PROD: "True"
  ALIGNMENTS_PATH: "/tmp/app/alignments/"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: peptipedia
  name: pod-peptipedia
spec:
  containers:
    - name: db
      image: postgres:17
      envFrom:
        - configMapRef:
            name: peptipedia
        - secretRef:
            name: peptipedia
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: peptipedia-db-init
          mountPath: /docker-entrypoint-initdb.d/:z
          readOnly: true
        - name: peptipedia-db-pvc
          mountPath: /var/lib/postgresql/data:U,Z
        - name: peptipedia-db-tmp
          mountPath: /var/run/postgresql:U

    - name: backend
      image: peptipedia_backend:latest
      restartPolicy: OnFailure
      envFrom:
        - configMapRef:
            name: peptipedia
        - secretRef:
            name: peptipedia
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      ports:
        - containerPort: 8000
          hostPort: 10001
      volumeMounts:
        - name: peptipedia-files
          mountPath: /app/files:Z
        - name: peptipedia-tmp
          mountPath: /tmp/app:U

    - name: frontend
      image: peptipedia_frontend:latest
      securityContext:
        runAsUser: 1002
        runAsGroup: 1002
      ports:
        - containerPort: 8080
          hostPort: 10002

  volumes:
    - name: peptipedia-db-init
      hostPath:
        path: ./db_init/
        type: DirectoryOrCreate
    - name: peptipedia-db-pvc
      persistentVolumeClaim:
        claimName: peptipedia-db-pvc
    - name: peptipedia-db-tmp
      emptyDir: { }
    - name: peptipedia-files
      hostPath:
        path: ./peptipedia_files/
        type: DirectoryOrCreate
    - name: peptipedia-tmp
      emptyDir: { }